In [94]:
import numpy as np
import tensorflow as tf
import pandas as pd
import re
import nltk

In [111]:
df=pd.read_csv('Restaurant_Reviews.tsv', sep='\t')
df

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [96]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [114]:
for i in range(len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df.loc[i, 'Review'])
    df.loc[i, 'Review'] = review.lower()
    df.loc[i, 'Review'] = review.strip()
df

                                                Review  Liked
0                              Wow    Loved this place      1
1                                    Crust is not good      0
2             Not tasty and the texture was just nasty      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                            Appetite instantly gone      0
997  Overall I was not impressed and would not go back      0
998  The whole experience was underwhelming  and I ...      0
999  Then  as if I hadn t wasted enough of my life ...      0

[1000 rows x 2 columns]

In [115]:
#Giving index numbers of the words
vocab_size=10000
encoded_reviews=[one_hot(d, vocab_size) for d in df['Review']]
encoded_reviews

[[5667, 7631, 7703, 1663],
 [7276, 4070, 4699, 5109],
 [4699, 7630, 3193, 1635, 1983, 7407, 3013, 9994],
 [2409,
  839,
  1690,
  1635,
  4887,
  9162,
  701,
  687,
  9423,
  3463,
  63,
  8451,
  3193,
  7631,
  5577],
 [1635, 4516, 9150, 1635, 5603, 7407, 8375, 3193, 4617, 552, 1635, 6881],
 [3167, 7086, 6490, 6009, 5154, 3193, 7086, 1317, 8179, 2910, 1599],
 [648, 5577, 648, 6912, 7154, 2838, 6763],
 [1635,
  2617,
  552,
  7439,
  5747,
  3193,
  5467,
  5520,
  2262,
  115,
  8688,
  652,
  2202,
  3064,
  2210,
  6914,
  9322,
  1569,
  3825,
  1783,
  2109,
  9777],
 [1635, 1318, 552, 8375, 957],
 [2109, 8375, 9117],
 [5965, 7407, 9518, 7841],
 [974, 4699, 6874, 3355],
 [1635,
  6222,
  8688,
  8394,
  5933,
  567,
  4617,
  8880,
  9150,
  567,
  7086,
  8688,
  8639,
  3178,
  5577,
  3711,
  1003,
  3064,
  1569,
  2254,
  6094],
 [7086, 3441, 1635, 9504, 7976, 7922, 6408, 624, 4639, 4514],
 [7086, 7407, 7944, 2510, 7086, 7407, 3435, 6362, 2838, 7407, 511, 5561],
 [7086, 7407, 531, 2510, 8394, 6327, 260, 1825, 8030],
 [1375, 9763],
 [5313, 7407, 2109, 8289, 9742, 823, 5965],
 [7703, 1663, 4070, 4699, 823, 2397, 9322, 1462, 1013, 3759],
 [1654, 4699, 7439, 9208, 7965],
 [1635, 2157, 260],
 [1635, 6832, 3219],
 [5965, 4070, 5799, 2025],
 [7086, 5520, 5933, 4904, 1635, 8441, 4070, 3013, 4389],
 [4617, 115, 8302],
 [2838, 2226, 9669, 1635, 279, 5350, 5057, 2243, 7703, 4271, 4070, 4617, 5109],
 [115, 1544, 6470, 2109, 5907, 2546, 1714, 8732],
 [7703, 9277, 823, 1635, 9605, 447, 8375, 4282, 216, 5491, 3193, 435, 1500],
 [852,
  5747,
  1200,
  8639,
  9166,
  4168,
  6832,
  8030,
  583,
  823,
  2274,
  8179,
  6832,
  7407,
  2138,
  8516,
  4168,
  951,
  7407,
  7620,
  7986,
  7439,
  2472,
  7407,
  3994,
  7970],
 [1635, 7053, 7407, 1635, 6919, 3711],
 [5799,
  2383,
  1511,
  3618,
  7439,
  2109,
  5598,
  1318,
  3193,
  7839,
  8732,
  4935,
  4070,
  2109,
  6494,
  4170],
 [7703, 7407, 7439, 1635, 262, 4861],
 [7086, 8267, 7703, 1663, 839, 7403, 3193, 7086, 5520, 4699, 9052, 2630],
 [4912,
  7439,
  2109,
  5109,
  6174,
  1663,
  8639,
  4118,
  2109,
  1855,
  6914,
  9383,
  5259,
  4256,
  6832,
  2081,
  5598,
  9918,
  2109,
  9422,
  3193,
  8771,
  7884],
 [8121, 7086, 7439, 7703, 1663, 2109, 2793],
 [1635,
  8030,
  7869,
  1599,
  6914,
  1635,
  2274,
  7407,
  2838,
  5577,
  7407,
  9518,
  9134],
 [9764, 9277, 3193, 5109, 6881],
 [791,
  5965,
  1635,
  5096,
  2202,
  334,
  6526,
  7439,
  7086,
  7407,
  6035,
  8870,
  9322,
  2472,
  365,
  8639,
  1635,
  4979],
 [8179, 1182, 4492, 8639, 2867, 7407, 2109, 5883],
 [5965, 2500],
 [1635, 4910, 1464, 3193, 2998],
 [2383,
  4070,
  4699,
  2109,
  4170,
  5109,
  4121,
  2838,
  974,
  3503,
  334,
  9993,
  2838,
  7841,
  7648],
 [5005,
  8639,
  9573,
  7519,
  5049,
  9636,
  552,
  5109,
  2510,
  2546,
  552,
  701,
  6364,
  839,
  1635,
  9809,
  4382,
  3193,
  648,
  6912,
  1317,
  8639,
  7752,
  5577,
  8732,
  5014,
  6914,
  6009,
  437],
 [9150,
  2109,
  4299,
  2810,
  4168,
  8390,
  7407,
  9518,
  1007,
  3193,
  3582,
  8375,
  5965],
 [2711, 7545, 6914, 4590, 624, 9383, 6914, 1635, 7053, 1344, 9998, 1635, 4931],
 [1635,
  8030,
  2629,
  7086,
  1654,
  7439,
  7407,
  1635,
  2097,
  8645,
  3193,
  1803,
  9600],
 [5577, 2226, 957, 5237, 1635, 6832, 4070, 4617, 2910, 7544],
 [1635, 5598, 4070, 5109, 4697, 6375, 3013, 9669],
 [961, 5467, 1317, 2109, 8951, 3013, 6874, 8639, 1865, 1683],
 [8179,
  9687,
  2586,
  5907,
  624,
  1635,
  2586,
  9796,
  7407,
  4617,
  7630,
  3193,
  1635,
  4507,
  3193,
  3885,
  7407,
  9518,
  1864],
 [2546,
  1647,
  1635,
  8841,
  3312,
  3193,
  5577,
  7407,
  5827,
  3193,
  1464,
  9150,
  1635,
  4888,
  624,
  2109,
  4762,
  8585,
  9150,
  1635,
  4819],
 [2472,
  365,
  7620,
  8448,
  9195,
  5130,
  2472,
  9139,
  8179,
  4478,
  8688,
  1675,
  598,
  2173,
  9150,
  1635,
  4979],
 [3461, 970, 6590, 4070, 4617, 5109],
 [115,
  1554,
  808,
  4880,
  9709,
  3673,
  3193,
  9594,
  6760,
  8639,
  8559,
  5256,
  5130,
  3673,
  8002,
  6912,
  5972,
  3461,
  6832],
 [1635, 3072, 7407, 3053],
 [7631, 5577, 435, 5047, 8375, 6832, 5228, 3193, 4146, 5603],
 [1635,
  4280,
  6197,
  1071,
  823,
  6552,
  3759,
  4070,
  5747,
  3399,
  8539,
  9259,
  930,
  8732,
  2109,
  2274],
 [4699, 5229, 6410, 3193, 7439, 299, 6914, 3971, 9208, 1635, 6429],
 [1635,
  5907,
  8688,
  3013,
  1635,
  9669,
  8138,
  6914,
  7902,
  8639,
  4699,
  3070,
  7208,
  1635,
  505,
  4935,
  7407,
  9775,
  6375],
 [1635, 730, 6117, 7407, 4699, 8030, 730, 2081, 5783, 3193, 1087],
 [9208,
  999,
  315,
  8639,
  2123,
  8179,
  9469,
  6090,
  7086,
  2615,
  8639,
  4610,
  5467,
  3070,
  8732,
  8130],
 [7703, 1663, 4058, 5601, 8732, 3461, 6020],
 [1635, 3750, 1511, 7965, 5008, 3193, 4032],
 [2546, 4230, 6786, 6874, 3355, 8016, 7648],
 [2546, 1511, 4617, 8303, 2546, 8267, 7703, 1663],
 [8375, 6832, 3193, 5965, 3053, 9277, 3193, 115, 3313, 2109, 8231, 8172],
 [4133, 2109, 8375, 9322, 9208, 5418, 4734],
 [5382,
  2197,
  3355,
  8732,
  2109,
  9870,
  9322,
  3193,
  5577,
  7407,
  3711,
  3013,
  5359,
  3219],
 [2546,
  1750,
  1635,
  6832,
  3193,
  3671,
  115,
  1554,
  1544,
  6823,
  6914,
  9319,
  3193,
  1635,
  870,
  9150,
  1635,
  6108,
  7407,
  5727],
 [2109, 8375, 9387, 8639, 1673, 2109, 8375],
 [1635,
  4170,
  1422,
  6863,
  3193,
  9695,
  3193,
  7076,
  2197,
  7857,
  3193,
  2560,
  567,
  2546,
  6413],
 [7392, 7392, 5109, 58, 7965, 1635, 9322],
 [1635, 5965, 7407, 4920],
 [5577,
  852,
  3070,
  1461,
  8639,
  9166,
  3461,
  7891,
  4935,
  7407,
  8192,
  7996,
  4979,
  9001,
  674],
 [7086,
  2430,
  7086,
  8966,
  1554,
  7048,
  2838,
  7703,
  1663,
  974,
  7230,
  2510,
  5577,
  4070,
  4888,
  6914,
  1635,
  203,
  2081,
  7086,
  648,
  6912,
  828,
  8179,
  8130,
  7095],
 [1635, 505, 8919, 4070, 2595, 1804, 8732, 3474, 5359, 7608],
 [808, 9518, 5237, 8866, 5965],
 [1635, 1797, 5159, 1318, 552, 9518, 5109, 3193, 820, 7608],
 [7927,
  4070,
  1635,
  9870,
  9322,
  7086,
  6031,
  652,
  8639,
  3461,
  1689,
  2166,
  3193,
  5577,
  7407,
  3435,
  5109],
 [2383,
  4070,
  4617,
  5229,
  5109,
  6832,
  823,
  3759,
  2838,
  7086,
  6526,
  6809,
  8732,
  248,
  5747,
  1738,
  5717,
  839,
  7462,
  8639,
  58,
  3193,
  3196],
 [5925,
  8016,
  4070,
  7439,
  8613,
  5747,
  7034,
  4275,
  4134,
  4473,
  9132,
  8834,
  6912,
  2268,
  8732,
  1635,
  368,
  4016,
  8639,
  1612,
  8639,
  6479,
  3064],
 [2598,
  823,
  3193,
  1635,
  1663,
  4308,
  7439,
  5747,
  8090,
  4889,
  8890,
  3193,
  8030,
  1199,
  2383,
  1738],
 [1635, 9934, 3193, 7951, 4697, 552, 8421],
 [7703, 1663, 447, 5577],
 [1635,
  2331,
  2604,
  5968,
  1511,
  4681,
  1386,
  7154,
  7439,
  2109,
  446,
  6379,
  7662,
  8639,
  1635,
  6248,
  6914,
  2109,
  7822,
  9944,
  8090],
 [7086,
  3233,
  1635,
  1599,
  3193,
  1635,
  7159,
  5272,
  2645,
  4617,
  5264,
  5467,
  1554,
  8639,
  2034],
 [1635, 791, 870, 8639, 8479, 3653, 2202, 1635, 6408, 5146, 9518, 8052],
 [7965, 7086, 1554, 8639, 3178, 4070, 1635, 6832, 7407, 3219],
 [6744, 1511, 8639, 8723, 8732],
 [8508, 7407, 6763, 3193, 4032],
 [823, 5065, 7703, 7407, 2109, 3517, 9566, 7716, 7393],
 [5577,
  2226,
  7439,
  2109,
  7392,
  4580,
  633,
  823,
  2397,
  8777,
  4134,
  5467,
  7103,
  755,
  4142,
  624,
  1635,
  8394,
  4016,
  9208,
  1635,
  633],
 [1544,
  652,
  8639,
  5005,
  8246,
  5080,
  6090,
  9329,
  1544,
  8880,
  1588,
  1035,
  823,
  5577,
  7648],
 [2738, 6085, 2166],
 [3178, 7402, 7402, 8639, 2397, 1303, 9398],
 [2546, 6511, 1544, 6874, 7648],
 [9329, 9052, 3355, 7648],
 [6832, 4607, 4912],
 [5577, 7407, 4699, 5109],
 [9150, 1635, 3064, 9687, 3461, 2787, 6258, 7392, 5109, 6832],
 [4168,
  8390,
  7407,
  909,
  3193,
  5130,
  2472,
  8267,
  6364,
  1635,
  3036,
  1734,
  3395,
  5488,
  3193,
  9800,
  5382,
  2472,
  3563,
  2304,
  8639,
  4168,
  4741,
  3193,
  1979,
  5382,
  8639,
  6874],
 [1635,
  8030,
  5109,
  2629,
  7407,
  4168,
  5096,
  2472,
  7407,
  9518,
  1636,
  3193,
  3825,
  1635,
  1492,
  1379,
  2226,
  5925],
 [2738, 2166, 823, 9286, 8732, 1635, 8068, 5467, 8792, 656, 5577],
 [7086,
  7631,
  3461,
  8601,
  6375,
  823,
  7703,
  5712,
  2389,
  1635,
  8841,
  7407,
  1464,
  3193,
  3461,
  5159,
  9344,
  552,
  4032],
 [7703, 4070, 5256, 6914, 1635, 1643, 8340, 2838, 7086, 1554, 652, 8639],
 [4617, 2546, 2197, 8639, 8636, 3193, 8688, 2109, 909, 7483],
 [1635,
  6832,
  7407,
  4032,
  4168,
  4222,
  7407,
  1007,
  3193,
  9292,
  3193,
  2546,
  1750,
  2109,
  8375,
  4170],
 [1635, 1895, 4070, 5228, 3193, 2383, 4070, 9646, 2385],
 [9329, 6874, 3355, 4634, 8483, 6364],
 [5990, 5109],
 [350, 4348, 6545, 1462, 2226, 9052, 1387, 4805, 4070, 4699, 2838, 5109],
 [9208,
  999,
  1461,
  1178,
  823,
  1903,
  9195,
  8879,
  3193,
  1635,
  6832,
  9590,
  3193,
  5577,
  9106,
  6912,
  2838,
  2586],
 [7703, 4070, 2109, 7392, 909, 9682, 2274, 4935, 4070, 6786, 823, 2109, 4492],
 [4762, 2558, 3193, 1464],
 [5109, 6881],
 [6547, 5577, 6364],
 [5577, 7407, 3435, 3013],
 [7086, 6031, 8688, 1643, 8403],
 [1923, 6914, 5005, 8639, 7123, 3064, 2109, 3227, 2081, 115, 1654],
 [9476,
  7086,
  9518,
  5229,
  381,
  1635,
  8771,
  3193,
  4420,
  6914,
  7703,
  1663,
  1635,
  1628,
  7393,
  7407,
  2109,
  6087,
  9566],
 [7086,
  3013,
  8002,
  6912,
  7662,
  2245,
  7703,
  1663,
  3864,
  8639,
  5839,
  1635,
  5431,
  6832,
  7086,
  1554,
  8880,
  1946,
  5130,
  115,
  1511,
  3658,
  5515,
  5162],
 [7053, 5965, 8639, 7161, 2081, 2838, 4070, 1635, 999, 6914, 3461, 8821],
 [5965, 7407, 9584, 3193, 1635, 5313, 7407, 435],
 [1635,
  4132,
  7965,
  8688,
  4142,
  3193,
  4168,
  3227,
  3523,
  4499,
  6340,
  447,
  8688,
  3227,
  9208,
  1635,
  2738,
  3193,
  7053,
  4561,
  8079,
  5577,
  7407,
  1635,
  2738,
  3227,
  2472,
  2226,
  8880,
  1946],
 [2546,
  6190,
  5467,
  4230,
  1554,
  8639,
  1818,
  9285,
  3316,
  8639,
  9166,
  5109,
  4348,
  2081,
  7703,
  1663,
  7392,
  5095,
  1635,
  209,
  2838,
  1313],
 [2267, 1500, 552, 8732, 505, 6914, 2109, 1643, 4217, 1214],
 [8421,
  4699,
  2109,
  1271,
  7703,
  1663,
  8732,
  2109,
  1971,
  6914,
  1071,
  3193,
  7086,
  8002,
  6912,
  1317,
  8639,
  5657,
  9322,
  9150,
  5237,
  4657,
  7086,
  6511,
  5775,
  5577,
  9208,
  2838],
 [7596, 6832, 5965, 3193, 8111],
 [7086, 4908, 6912, 524],
 [6786,
  823,
  7027,
  9423,
  1635,
  5144,
  8732,
  1635,
  888,
  4047,
  9329,
  524,
  4634,
  9322,
  7086,
  7787,
  823,
  3759],
 [7703, 1663, 4070, 9387, 957, 6094, 8732, 1454, 6832],
 [5457, 9328, 8194],
 [115,
  1554,
  2109,
  5109,
  4516,
  6914,
  6832,
  9659,
  2109,
  4039,
  7120,
  8951,
  2109,
  6235,
  6408,
  6700,
  2109,
  5995,
  2024,
  8302,
  3193,
  9383,
  7630,
  3858],
 [1635, 4510, 4070, 6605],
 [4032, 3674, 4339, 5109, 8309, 6914, 8007, 1497, 350, 8908, 624, 6560, 4459],
 [8375,
  3710,
  823,
  920,
  5577,
  2226,
  4617,
  5109,
  5130,
  5467,
  1975,
  8016,
  8870,
  368,
  3710,
  9329,
  4699,
  9475,
  2397,
  73],
 [7086, 8688, 2109, 4283, 2938, 6085, 8016],
 [7703, 4070, 5256, 6914, 1635, 2738, 9912, 624, 6832, 823, 3759],
 [2472,
  7407,
  46,
  6605,
  3193,
  7392,
  2383,
  1511,
  4617,
  267,
  368,
  6535,
  7086,
  974,
  3233,
  8639,
  3439,
  9208,
  1690,
  2109,
  4578,
  823,
  3759],
 [8179,
  1552,
  7407,
  1544,
  6656,
  3193,
  2472,
  2202,
  9383,
  7392,
  8375,
  5603,
  7990],
 [8002, 6912, 5598, 5577],
 [1635, 5096, 9106, 6912, 1636, 7401, 435, 3193, 3982, 9698, 9150, 9195],
 [8179,
  4478,
  3193,
  7086,
  7031,
  1689,
  8016,
  3193,
  552,
  9518,
  7084,
  624,
  1635,
  6832,
  3193,
  5965],
 [3193,
  1635,
  279,
  808,
  8688,
  4617,
  5229,
  5627,
  7859,
  3193,
  9106,
  6912,
  9518,
  7630,
  8639,
  334],
 [4762,
  475,
  6914,
  63,
  3070,
  4162,
  2081,
  7086,
  6526,
  7439,
  7703,
  7407,
  9163,
  8639,
  4702,
  3064,
  1635,
  9382,
  6832],
 [1635, 5447, 1511, 4837, 3193, 1635, 1663, 1067, 4070, 7608, 2857],
 [1635,
  5603,
  4070,
  4133,
  1248,
  6832,
  1599,
  4070,
  7462,
  6760,
  5965,
  4070,
  46,
  9742],
 [1635,
  5965,
  7407,
  2109,
  8289,
  9742,
  1233,
  2838,
  552,
  5839,
  839,
  1344,
  5047,
  4617,
  1635,
  6832,
  7407,
  5925,
  823,
  2109,
  9742,
  9403],
 [7086, 3313, 5577, 2077, 6760],
 [2546,
  5783,
  4168,
  5096,
  7527,
  2109,
  2793,
  7996,
  9716,
  8639,
  368,
  583,
  3193,
  8617,
  9195],
 [8179,
  528,
  3193,
  7086,
  365,
  823,
  1635,
  2255,
  6914,
  1635,
  6644,
  3193,
  2546,
  552,
  2697,
  3193,
  7032,
  9669,
  3316],
 [7703, 4070, 2109, 8375, 2274, 9208, 1635, 1899, 845],
 [2546, 6409, 8732, 6804, 37, 8130, 823, 2758],
 [46, 2838, 365, 624, 1635, 5907, 7407, 2198],
 [9383, 5483, 8375, 1599, 2430, 8016],
 [1635, 1500, 4070, 435, 3193, 1635, 9028, 4070, 4133, 4837],
 [7703,
  7407,
  2109,
  8458,
  2758,
  4979,
  1635,
  7903,
  1635,
  368,
  6644,
  2081,
  3711,
  5228,
  3193,
  1464,
  2226,
  7608,
  5359,
  7608,
  2326],
 [7086,
  1647,
  1635,
  8305,
  3971,
  3193,
  5577,
  7407,
  1635,
  1182,
  9322,
  7086,
  4230,
  8688,
  7392,
  8194,
  3971,
  9993,
  7462,
  8539,
  1993,
  7667,
  4689,
  9170],
 [7703, 1663, 4070, 5109],
 [2845,
  2546,
  4492,
  1554,
  5095,
  1635,
  5730,
  9150,
  5015,
  6644,
  2510,
  8508,
  2546,
  1647,
  7407,
  2198],
 [7086, 365, 3355, 7927, 9993, 115, 8291, 3193, 3711, 4699, 4988],
 [7086, 7407, 7032, 7425],
 [3461, 5603, 4070, 9328, 3193, 5261, 3999],
 [1030, 9208, 7965, 102],
 [2274, 4070, 4133, 7720, 2081, 1544, 2109, 2268],
 [4032],
 [7703,
  1663,
  4070,
  7165,
  6760,
  5256,
  6914,
  1635,
  2738,
  4561,
  8639,
  7752,
  823,
  1635,
  1093,
  6127,
  2409],
 [4617, 8002, 6912, 6874, 2383, 961, 5467, 1511, 6511, 8732, 5109, 6832],
 [7086, 6031, 1544, 652, 8963, 4617, 5237],
 [903, 4070, 3396, 2590],
 [2546,
  5799,
  1647,
  1635,
  7760,
  3193,
  4528,
  5907,
  1635,
  295,
  552,
  1185,
  3193,
  1635,
  9796,
  7180,
  8688,
  8735,
  7154],
 [7703,
  7392,
  4070,
  2245,
  3759,
  9584,
  7716,
  7411,
  8639,
  9052,
  9669,
  6760,
  8639,
  1635,
  3958,
  5584,
  8639,
  1635,
  7511,
  2838,
  1554,
  8394,
  6881,
  2880],
 [1635, 9821, 1511, 9518, 435],
 [3485,
  1635,
  1218,
  1854,
  4070,
  2109,
  8919,
  2838,
  4070,
  4699,
  8639,
  9052,
  5435,
  8732,
  808,
  6545],
 [8508,
  9150,
  1635,
  5603,
  4070,
  9576,
  3193,
  2546,
  552,
  5799,
  4160,
  2838,
  115,
  2202,
  3219,
  2664,
  8732,
  4168,
  2955,
  4684],
 [7629,
  7086,
  6321,
  2468,
  9150,
  5747,
  9423,
  1313,
  7478,
  839,
  1635,
  368,
  3555,
  2081,
  7086,
  7787,
  4699,
  4425,
  8639,
  6874,
  3355],
 [1635, 5965, 8016, 2500, 2109, 2793, 8639, 9052, 2422],
 [1635, 8403, 4070, 2900, 3193, 2375, 6292, 6685, 2109, 9117, 6914, 6343],
 [4699,
  2109,
  7207,
  334,
  2081,
  6786,
  2109,
  1663,
  8639,
  1975,
  3355,
  8639,
  8870,
  5549,
  823,
  2109,
  6292],
 [2546,
  7180,
  5291,
  2383,
  8732,
  8130,
  624,
  8394,
  5256,
  5894,
  8639,
  145,
  4168,
  1351],
 [1635,
  5598,
  8688,
  3399,
  8394,
  5714,
  1635,
  8479,
  1067,
  7407,
  3994,
  8421,
  1635,
  5598,
  7407,
  6593,
  3193,
  2383,
  7407,
  8394,
  5167,
  5714],
 [7086,
  5799,
  946,
  4699,
  8639,
  1917,
  5577,
  3355,
  2510,
  4168,
  5313,
  6783,
  7439,
  6810,
  7407,
  9150,
  1635,
  7882,
  6914,
  512,
  2109,
  4280,
  6197],
 [7086, 7334, 3064, 8639, 9052, 8963, 4617, 5136],
 [5577, 7407, 4210, 8847],
 [3233,
  7703,
  1663,
  9457,
  1635,
  209,
  5130,
  7086,
  1317,
  9203,
  3687,
  2081,
  4699,
  4765,
  823,
  8664,
  7401,
  5714],
 [7086, 1647, 1635, 2026, 8833, 5811, 1543, 4935, 7407, 5799, 2590],
 [1635,
  6832,
  3966,
  4935,
  2546,
  6413,
  2081,
  5577,
  3966,
  7996,
  4979,
  2546,
  5520,
  1554,
  3736],
 [9771, 7712],
 [567, 7086, 7392, 7439, 2383, 4070, 1635, 4915, 7835],
 [5799,
  552,
  5839,
  8450,
  2254,
  3193,
  2177,
  3193,
  3734,
  2202,
  5159,
  8271,
  624,
  903,
  6374,
  9150,
  4162,
  9518,
  8006,
  3193,
  9518,
  5109],
 [5467, 8834, 5406, 2468, 3658, 1635, 4032, 6832],
 [4473, 6914, 1635, 620, 5272, 552, 909],
 [5130, 8179, 1351, 4607, 5256, 6914, 1635, 6183, 7407, 8944],
 [7086,
  8688,
  2109,
  5907,
  624,
  1635,
  5065,
  3193,
  9383,
  5811,
  8007,
  8732,
  1803,
  3193,
  1675,
  9068,
  2595,
  6626],
 [7086,
  7787,
  4699,
  7392,
  6362,
  2245,
  1519,
  2226,
  7407,
  2321,
  2738,
  8450,
  4872,
  823,
  1635,
  7912,
  839,
  6671,
  6914,
  1093,
  7507],
 [1635, 2738, 1663, 8639, 6874, 8732, 2109, 7630, 8830, 6914, 1599],
 [1635, 4992, 9646, 9150, 3185, 3994, 7441],
 [7086, 6031, 1544, 652, 7996, 3833, 7401, 7515, 8966],
 [9518, 435, 1500],
 [5577, 4070, 823, 1635, 4147],
 [7086,
  8688,
  6823,
  5109,
  1027,
  1386,
  7703,
  1663,
  2081,
  5577,
  4534,
  8870,
  1075,
  7086,
  5520,
  1554,
  187,
  6914],
 [6832, 7407, 8375, 3193, 4617, 7407, 1635, 631],
 [1635, 8516, 7839, 648, 6912, 710],
 [8375, 1816, 209],
 [5965, 4070, 435, 3193, 7885],
 [9518, 5109, 1689, 209],
 [7086,
  6031,
  861,
  8016,
  9993,
  3193,
  7703,
  7407,
  1635,
  1182,
  3193,
  9843,
  9322,
  7086,
  6031,
  1473,
  4352,
  9993,
  7703,
  1663],
 [1635, 7053, 7393, 8880],
 [4492, 1554, 652, 5747, 9423, 1313, 9208, 7703, 1663],
 [1635, 9636, 1511, 5995, 1957, 2228, 5025, 1913, 1967, 2351, 6311, 3721],
 [961,
  2838,
  3372,
  1544,
  9951,
  3064,
  7086,
  974,
  1554,
  7074,
  2109,
  8732,
  6362,
  2081,
  9150,
  1635,
  368,
  9687,
  6914,
  1635,
  9605,
  4134,
  7703,
  3372,
  7407,
  8961,
  7407,
  1635,
  1383],
 [8732,
  1386,
  8130,
  2546,
  2546,
  7103,
  6974,
  8732,
  6529,
  5907,
  5130,
  2546,
  9139,
  2838,
  5577,
  9106,
  6912,
  5925,
  1865,
  9322,
  6984],
 [8179, 7004, 7631, 1635, 6919, 7759],
 [1342, 6912, 6874, 3355],
 [46, 7630],
 [5313, 7407, 5109, 3837],
 [4122, 3193, 4699, 5109],
 [1635, 299, 7103, 1511, 4032],
 [4935, 1511, 9399, 3193, 4699, 823, 1635, 8068],
 [1635, 6832, 4070, 1741, 4617, 1351, 6748],
 [1635,
  8378,
  2409,
  4070,
  4819,
  4617,
  5467,
  8834,
  8030,
  3179,
  4699,
  145,
  2109,
  7720,
  8378,
  9258,
  5467,
  8002,
  6912,
  5716,
  1569,
  5149,
  8732,
  5968,
  8639,
  3467],
 [1635, 5965, 7407, 2109, 6087, 4765],
 [430,
  8223,
  3315,
  2292,
  4271,
  2639,
  7965,
  294,
  9319,
  3193,
  7811,
  3193,
  6914,
  940,
  2383,
  4070,
  4171,
  9208,
  1635,
  583],
 [9994,
  7703,
  5272,
  8732,
  2468,
  7462,
  6364,
  6914,
  6923,
  3193,
  4381,
  6340,
  8834,
  4391,
  8834,
  1975,
  823],
 [5577, 7407, 8344, 957, 9967, 4699, 4121, 5714, 7401, 3013, 5237],
 [7086, 7631, 1635, 903, 7951, 236],
 [7703, 4070, 5747, 6281, 1507],
 [1635, 8647, 9208, 9834, 4133, 9432, 9195, 6526, 4617, 8225, 3193, 8949],
 [5359, 8732, 1635, 4538, 5799, 1953],
 [7703,
  4070,
  1635,
  1663,
  4134,
  7086,
  1182,
  8688,
  1599,
  3193,
  5577,
  7407,
  3219],
 [7703,
  5228,
  7393,
  2202,
  7703,
  1663,
  2109,
  4492,
  9159,
  9904,
  2546,
  1511,
  823,
  9286,
  7648],
 [961,
  1635,
  6832,
  8875,
  6912,
  5237,
  4121,
  8732,
  5467,
  9136,
  5972,
  9964,
  624,
  1635,
  7744,
  2226,
  7053,
  8012,
  9189,
  1344],
 [9518, 9518, 3049, 4329],
 [1647,
  2109,
  4308,
  6082,
  1750,
  2109,
  9392,
  3037,
  2838,
  7407,
  1880,
  4867,
  5091,
  8634,
  3505,
  3711,
  2500],
 [8375,
  1663,
  8639,
  1554,
  2109,
  9928,
  9695,
  3193,
  5406,
  1865,
  3193,
  7965,
  1208,
  5817,
  5359,
  1635,
  4096,
  1511,
  9192,
  624,
  3226,
  2226],
 [961, 5577, 552, 2048, 8639, 3313, 2468, 8735, 5601, 115, 4230, 1554, 5577],
 [1635,
  1425,
  8079,
  4710,
  4710,
  7902,
  3193,
  1979,
  8079,
  7862,
  7902,
  2713,
  1979,
  8079,
  2558,
  459,
  7608,
  4171,
  6914,
  1635,
  5272,
  8688,
  7213,
  9150,
  2468],
 [7086,
  4230,
  3178,
  2838,

In [116]:
max_length=max([len(d) for d in encoded_reviews])
padded_reviews=pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[5667, 7631, 7703, ...,    0,    0,    0],
       [7276, 4070, 4699, ...,    0,    0,    0],
       [4699, 7630, 3193, ...,    0,    0,    0],
       ...,
       [8121, 7086, 7407, ...,    0,    0,    0],
       [1635, 1109, 7393, ...,    0,    0,    0],
       [9136, 5359,  961, ...,    0,    0,    0]],
      shape=(1000, 32), dtype=int32)

In [81]:
help(pad_sequences)

Help on function pad_sequences in module keras.src.utils.sequence_utils:

pad_sequences(sequences, maxlen=None, dtype='int32', padding='pre', truncating='pre', value=0.0)
    Pads sequences to the same length.

    This function transforms a list (of length `num_samples`)
    of sequences (lists of integers)
    into a 2D NumPy array of shape `(num_samples, num_timesteps)`.
    `num_timesteps` is either the `maxlen` argument if provided,
    or the length of the longest sequence in the list.

    Sequences that are shorter than `num_timesteps`
    are padded with `value` until they are `num_timesteps` long.

    Sequences longer than `num_timesteps` are truncated
    so that they fit the desired length.

    The position where padding or truncation happens is determined by
    the arguments `padding` and `truncating`, respectively.
    Pre-padding or removing values from the beginning of the sequence is the
    default.

    >>> sequence = [[1], [2, 3], [4, 5, 6]]
    >>> keras.utils.pad_sequences(sequence)
    array([[0, 0, 1],
           [0, 2, 3],
           [4, 5, 6]], dtype=int32)

    >>> keras.utils.pad_sequences(sequence, value=-1)
    array([[-1, -1,  1],
           [-1,  2,  3],
           [ 4,  5,  6]], dtype=int32)

    >>> keras.utils.pad_sequences(sequence, padding='post')
    array([[1, 0, 0],
           [2, 3, 0],
           [4, 5, 6]], dtype=int32)

    >>> keras.utils.pad_sequences(sequence, maxlen=2)
    array([[0, 1],
           [2, 3],
           [5, 6]], dtype=int32)

    Args:
        sequences: List of sequences (each sequence is a list of integers).
        maxlen: Optional Int, maximum length of all sequences. If not provided,
            sequences will be padded to the length of the longest individual
            sequence.
        dtype: (Optional, defaults to `"int32"`). Type of the output sequences.
            To pad sequences with variable length strings, you can use `object`.
        padding: String, "pre" or "post" (optional, defaults to `"pre"`):
            pad either before or after each sequence.
        truncating: String, "pre" or "post" (optional, defaults to `"pre"`):
            remove values from sequences larger than
            `maxlen`, either at the beginning or at the end of the sequences.
        value: Float or String, padding value. (Optional, defaults to `0.`)

    Returns:
        NumPy array with shape `(len(sequences), maxlen)`

In [117]:
embedded_vector_size=5
model=Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name='embedding' ))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

d:\git_prac\NLP\.venv311\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [118]:
X=padded_reviews
y=df.iloc[:, 1]
X

array([[5667, 7631, 7703, ...,    0,    0,    0],
       [7276, 4070, 4699, ...,    0,    0,    0],
       [4699, 7630, 3193, ...,    0,    0,    0],
       ...,
       [8121, 7086, 7407, ...,    0,    0,    0],
       [1635, 1109, 7393, ...,    0,    0,    0],
       [9136, 5359,  961, ...,    0,    0,    0]],
      shape=(1000, 32), dtype=int32)

In [119]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, batch_size=32)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5270 - loss: 0.6928
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6610 - loss: 0.6870
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7380 - loss: 0.6805
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7600 - loss: 0.6718
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7990 - loss: 0.6595
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8270 - loss: 0.6433
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.8620 - loss: 0.6233
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8830 - loss: 0.5991
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8900 - loss: 0.5717
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8990 - loss: 0.5414

In [120]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 32, 5)          │        50,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_7 (Flatten)             │ (None, 160)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           161 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 150,485 (587.84 KB)

 Trainable params: 50,161 (195.94 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 100,324 (391.89 KB)

In [121]:
model.evaluate(X,y)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.9090 - loss: 0.5212

[0.5212224721908569, 0.9089999794960022]

In [122]:
model.get_layer('embedding').get_weights()[0]

array([[-0.01145842, -0.04016282,  0.03682453, -0.03725497,  0.04294382],
       [ 0.01266683,  0.03472258, -0.0482116 ,  0.01416024, -0.01070535],
       [-0.00445373, -0.03090613, -0.02783087, -0.01920329,  0.02171738],
       ...,
       [ 0.01828439,  0.00140122,  0.01590181,  0.0288333 , -0.0232108 ],
       [ 0.01911911,  0.01584153, -0.03306593,  0.09475888, -0.12033331],
       [ 0.04005729, -0.00916981, -0.02863294,  0.04730011, -0.00490508]],
      shape=(10000, 5), dtype=float32)

In [123]:
(padded_reviews)[0]

array([5667, 7631, 7703, 1663,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [124]:
print(model.predict(padded_reviews)[0])

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[0.6335859]